// ------------------------------------------------------
// Code generated by Papyrus Java
// ------------------------------------------------------
package com.coen6312.ocs.bean;

import java.util.Date;

/**
 * The Class AppointmentBean.
 */
public class AppointmentBean {
	private String appointmentID;
	private String doctorID;
	private String patientID;
	private Date appointmentDate;
	private String appointmentTime;
	
	/**
	 * Gets the appointment ID.
	 *
	 * @return the appointment ID
	 */
	public String getAppointmentID() {
		return appointmentID;
	}
	
	/**
	 * Sets the appointment ID.
	 *
	 * @param appointmentID the new appointment ID
	 */
	public void setAppointmentID(String appointmentID) {
		this.appointmentID = appointmentID;
	}
	
	/**
	 * Gets the doctor ID.
	 *
	 * @return the doctor ID
	 */
	public String getDoctorID() {
		return doctorID;
	}
	
	/**
	 * Sets the doctor ID.
	 *
	 * @param doctorID the new doctor ID
	 */
	public void setDoctorID(String doctorID) {
		this.doctorID = doctorID;
	}
	
	/**
	 * Gets the patient ID.
	 *
	 * @return the patient ID
	 */
	public String getPatientID() {
		return patientID;
	}
	
	/**
	 * Sets the patient ID.
	 *
	 * @param patientID the new patient ID
	 */
	public void setPatientID(String patientID) {
		this.patientID = patientID;
	}
	
	/**
	 * Gets the appointment date.
	 *
	 * @return the appointment date
	 */
	public Date getAppointmentDate() {
		return appointmentDate;
	}
	
	/**
	 * Sets the appointment date.
	 *
	 * @param appointmentDate the new appointment date
	 */
	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}
	
	/**
	 * Gets the appointment time.
	 *
	 * @return the appointment time
	 */
	public String getAppointmentTime() {
		return appointmentTime;
	}
	
	/**
	 * Sets the appointment time.
	 *
	 * @param appointmentTime the new appointment time
	 */
	public void setAppointmentTime(String appointmentTime) {
		this.appointmentTime = appointmentTime;
	}
	
}
