// ------------------------------------------------------
// Code generated by Papyrus Java
// ------------------------------------------------------
package com.coen6312.ocs.bean;

/**
 * The Class CredentialsBean.
 */
public class CredentialsBean {
	private String userID;
	private String password;
	private String userType;
	private int loginStatus;
	
	/**
	 * Gets the user ID.
	 *
	 * @return the user ID
	 */
	public String getUserID() {
		return userID;
	}
	
	/**
	 * Sets the user ID.
	 *
	 * @param userID the new user ID
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}
	
	/**
	 * Gets the password.
	 *
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}
	
	/**
	 * Sets the password.
	 *
	 * @param password the new password
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
	/**
	 * Gets the user type.
	 *
	 * @return the user type
	 */
	public String getUserType() {
		return userType;
	}
	
	/**
	 * Sets the user type.
	 *
	 * @param userType the new user type
	 */
	public void setUserType(String userType) {
		this.userType = userType;
	}
	
	/**
	 * Gets the login status.
	 *
	 * @return the login status
	 */
	public int getLoginStatus() {
		return loginStatus;
	}
	
	/**
	 * Sets the login status.
	 *
	 * @param loginStatus the new login status
	 */
	public void setLoginStatus(int loginStatus) {
		this.loginStatus = loginStatus;
	}
	
}
