// ------------------------------------------------------
// Code generated by Papyrus Java
// ------------------------------------------------------
package com.coen6312.ocs.bean;

import java.util.Date;

/**
 * The Class DoctorBean.
 */
public class DoctorBean {
private String doctorID;
private String doctorName;
private Date dateOfBirth;
private Date dateOfJoining;
private String gender;
private String qualification;
private String specialization;
private int yearsOfExperience;
private String street;
private String location;
private String city;
private String state;
private String pincode;
private String contactNumber;
private String emailID;

/**
 * Gets the doctor ID.
 *
 * @return the doctor ID
 */
public String getDoctorID() {
	return doctorID;
}

/**
 * Sets the doctor ID.
 *
 * @param doctorID the new doctor ID
 */
public void setDoctorID(String doctorID) {
	this.doctorID = doctorID;
}

/**
 * Gets the doctor name.
 *
 * @return the doctor name
 */
public String getDoctorName() {
	return doctorName;
}

/**
 * Sets the doctor name.
 *
 * @param doctorName the new doctor name
 */
public void setDoctorName(String doctorName) {
	this.doctorName = doctorName;
}

/**
 * Gets the date of birth.
 *
 * @return the date of birth
 */
public Date getDateOfBirth() {
	return dateOfBirth;
}

/**
 * Sets the date of birth.
 *
 * @param dateOfBirth the new date of birth
 */
public void setDateOfBirth(Date dateOfBirth) {
	this.dateOfBirth = dateOfBirth;
}

/**
 * Gets the date of joining.
 *
 * @return the date of joining
 */
public Date getDateOfJoining() {
	return dateOfJoining;
}

/**
 * Sets the date of joining.
 *
 * @param dateOfJoining the new date of joining
 */
public void setDateOfJoining(Date dateOfJoining) {
	this.dateOfJoining = dateOfJoining;
}

/**
 * Gets the gender.
 *
 * @return the gender
 */
public String getGender() {
	return gender;
}

/**
 * Sets the gender.
 *
 * @param gender the new gender
 */
public void setGender(String gender) {
	this.gender = gender;
}

/**
 * Gets the qualification.
 *
 * @return the qualification
 */
public String getQualification() {
	return qualification;
}

/**
 * Sets the qualification.
 *
 * @param qualification the new qualification
 */
public void setQualification(String qualification) {
	this.qualification = qualification;
}

/**
 * Gets the specialization.
 *
 * @return the specialization
 */
public String getSpecialization() {
	return specialization;
}

/**
 * Sets the specialization.
 *
 * @param specialization the new specialization
 */
public void setSpecialization(String specialization) {
	this.specialization = specialization;
}

/**
 * Gets the years of experience.
 *
 * @return the years of experience
 */
public int getYearsOfExperience() {
	return yearsOfExperience;
}

/**
 * Sets the years of experience.
 *
 * @param yearsOfExperience the new years of experience
 */
public void setYearsOfExperience(int yearsOfExperience) {
	this.yearsOfExperience = yearsOfExperience;
}

/**
 * Gets the street.
 *
 * @return the street
 */
public String getStreet() {
	return street;
}

/**
 * Sets the street.
 *
 * @param street the new street
 */
public void setStreet(String street) {
	this.street = street;
}

/**
 * Gets the location.
 *
 * @return the location
 */
public String getLocation() {
	return location;
}

/**
 * Sets the location.
 *
 * @param location the new location
 */
public void setLocation(String location) {
	this.location = location;
}

/**
 * Gets the city.
 *
 * @return the city
 */
public String getCity() {
	return city;
}

/**
 * Sets the city.
 *
 * @param city the new city
 */
public void setCity(String city) {
	this.city = city;
}

/**
 * Gets the state.
 *
 * @return the state
 */
public String getState() {
	return state;
}

/**
 * Sets the state.
 *
 * @param state the new state
 */
public void setState(String state) {
	this.state = state;
}

/**
 * Gets the pincode.
 *
 * @return the pincode
 */
public String getPincode() {
	return pincode;
}

/**
 * Sets the pincode.
 *
 * @param pincode the new pincode
 */
public void setPincode(String pincode) {
	this.pincode = pincode;
}

/**
 * Gets the contact number.
 *
 * @return the contact number
 */
public String getContactNumber() {
	return contactNumber;
}

/**
 * Sets the contact number.
 *
 * @param contactNumber the new contact number
 */
public void setContactNumber(String contactNumber) {
	this.contactNumber = contactNumber;
}

/**
 * Gets the email ID.
 *
 * @return the email ID
 */
public String getEmailID() {
	return emailID;
}

/**
 * Sets the email ID.
 *
 * @param emailID the new email ID
 */
public void setEmailID(String emailID) {
	this.emailID = emailID;
}

}	
