// ------------------------------------------------------
// Code generated by Papyrus Java
// ------------------------------------------------------
package com.coen6312.ocs.bean;

import java.util.Date;

/**
 * The Class PatientBean.
 */
public class PatientBean {
	private String patientID;
	private String userID;
	private Date appointmentDate;
	private String ailmentType;
	private String ailmentDetails;
	private String diagnosisHistory;
	
	/**
	 * Gets the patient ID.
	 *
	 * @return the patient ID
	 */
	public String getPatientID() {
		return patientID;
	}
	
	/**
	 * Sets the patient ID.
	 *
	 * @param patientID the new patient ID
	 */
	public void setPatientID(String patientID) {
		this.patientID = patientID;
	}
	
	/**
	 * Gets the user ID.
	 *
	 * @return the user ID
	 */
	public String getUserID() {
		return userID;
	}
	
	/**
	 * Sets the user ID.
	 *
	 * @param userID the new user ID
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}
	
	/**
	 * Gets the appointment date.
	 *
	 * @return the appointment date
	 */
	public Date getAppointmentDate() {
		return appointmentDate;
	}
	
	/**
	 * Sets the appointment date.
	 *
	 * @param appointmentDate the new appointment date
	 */
	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}
	
	/**
	 * Gets the ailment type.
	 *
	 * @return the ailment type
	 */
	public String getAilmentType() {
		return ailmentType;
	}
	
	/**
	 * Sets the ailment type.
	 *
	 * @param ailmentType the new ailment type
	 */
	public void setAilmentType(String ailmentType) {
		this.ailmentType = ailmentType;
	}
	
	/**
	 * Gets the ailment details.
	 *
	 * @return the ailment details
	 */
	public String getAilmentDetails() {
		return ailmentDetails;
	}
	
	/**
	 * Sets the ailment details.
	 *
	 * @param ailmentDetails the new ailment details
	 */
	public void setAilmentDetails(String ailmentDetails) {
		this.ailmentDetails = ailmentDetails;
	}
	
	/**
	 * Gets the diagnosis history.
	 *
	 * @return the diagnosis history
	 */
	public String getDiagnosisHistory() {
		return diagnosisHistory;
	}
	
	/**
	 * Sets the diagnosis history.
	 *
	 * @param diagnosisHistory the new diagnosis history
	 */
	public void setDiagnosisHistory(String diagnosisHistory) {
		this.diagnosisHistory = diagnosisHistory;
	}
	
}
