// ------------------------------------------------------
// Code generated by Papyrus Java
// ------------------------------------------------------
package com.coen6312.ocs.bean;

/**
 * The Class ScheduleBean.
 */
public class ScheduleBean {
	private String scheduleID;
	private String doctorID;
	private String availableDays;
	private String slots;
	
	/**
	 * Gets the schedule ID.
	 *
	 * @return the schedule ID
	 */
	public String getScheduleID() {
		return scheduleID;
	}
	
	/**
	 * Sets the schedule ID.
	 *
	 * @param scheduleID the new schedule ID
	 */
	public void setScheduleID(String scheduleID) {
		this.scheduleID = scheduleID;
	}
	
	/**
	 * Gets the doctor ID.
	 *
	 * @return the doctor ID
	 */
	public String getDoctorID() {
		return doctorID;
	}
	
	/**
	 * Sets the doctor ID.
	 *
	 * @param doctorID the new doctor ID
	 */
	public void setDoctorID(String doctorID) {
		this.doctorID = doctorID;
	}
	
	/**
	 * Gets the available days.
	 *
	 * @return the available days
	 */
	public String getAvailableDays() {
		return availableDays;
	}
	
	/**
	 * Sets the available days.
	 *
	 * @param availableDays the new available days
	 */
	public void setAvailableDays(String availableDays) {
		this.availableDays = availableDays;
	}
	
	/**
	 * Gets the slots.
	 *
	 * @return the slots
	 */
	public String getSlots() {
		return slots;
	}
	
	/**
	 * Sets the slots.
	 *
	 * @param slots the new slots
	 */
	public void setSlots(String slots) {
		this.slots = slots;
	}
	
}
