// ------------------------------------------------------
// Code generated by Papyrus Java
// ------------------------------------------------------
package com.coen6312.ocs.util;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 * The Class DBUtil.
 */
public class DBUtil {
	
	/**
	 * Gets the connection.
	 *
	 * @return the connection
	 * @throws ClassNotFoundException the class not found exception
	 * @throws SQLException the SQL exception
	 */
	public static  Connection getConnection() throws ClassNotFoundException, SQLException{
		Connection connection;
		Class.forName("oracle.jdbc.driver.OracleDriver");
		//connection=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","admin","admin");
		connection=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1522:orcl","SYSTEM","admin");
		return connection;
	}
}
